### ISSUE TITLE
RSS and Atom

### ISSUE THREAD

**Issue by abomadi** [YAFNET/YAFNET-DNN#10]
Before and after updating to the new version 2.2.0 i still have this error for the rss

ActiveTabID:401
ActiveTabName:المنتدى
RawURL:/forum1/g/rsstopic/pg/4/ft/0/f/7/default
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://www.website.com/forum1/g/topics/f/7/name/%D8%A8%D8%B1%D8%A7%D9%85%D8%AC%20%D8%AA%D8%BA%D8%B0%D9%8A%D8%A9/default
UserAgent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:95b1d8ec-219c-4fd1-8f1e-90fa95b9c7bf
InnerException:Invalid URI: The format of the URI could not be determined.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:System.Uri.CreateThis
StackTrace:
Message:
DotNetNuke.Services.Exceptions.PageLoadException: Invalid URI: The format of the URI could not be determined. ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at YAF.Core.Syndication.YafSyndicationFeed..ctor(String subTitle, YafRssFeeds feedType, Int32 sf, String urlAlphaNum)
   at YAF.Pages.rsstopic.GetTopicsFeed(YafSyndicationFeed& feed, YafRssFeeds feedType, Boolean atomFeedByVar, String lastPostIcon, String lastPostName, Int32 forumId)
   at YAF.Pages.rsstopic.Page_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---

**Comment by w8tcha** [comment]
What is your baseurlmask setting in the board settings?

**Comment by abomadi** [comment]
http://en.website.com

**Comment by abomadi** [comment]
sorry the above is in the config file but in board settings is www.website.com

**Comment by w8tcha** [comment]
Well my guess would be that uri can not handle unicode letters.

try to change the url rewriting mode in the web.config under appSettings to

```xml
<add key="YAF.URLRewritingMode" value="Translit" />
```

or remove the line

**Comment by abomadi** [comment]
Removing the line fixed the issue, Thanks
