### ISSUE TITLE
insert attachment error

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#18]
after successfully added the attachment when the attachment inserted into text "[attach]1[/attach]" by clicking on file name, the below error has accord
<code>
InnerMessage:Column 'HasAttachments' does not belong to table Table.
InnerStackTrace:
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRowExtensions.Field[T](DataRow row, String columnName)
   at YAF.Types.Objects.TypedMessageList..ctor(DataRow row)
   at YAF.Classes.Data.LegacyDb.b__b(DataRow t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at YAF.Core.Services.YafSendNotification.ToWatchingUsers(Int32 newMessageId)
   at YAF.Pages.postmessage.PostReply_Click(Object sender, EventArgs e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
</code>

however, after the go to post the file was added to post.
Also the attachment dialog doesn't close (or any action) after file upload, and for view the attached file the page should be refreshed!

**Comment by w8tcha** [comment]
Please run the yaf upgrade wizard manually to resolve the error in 2.2.1 beta 1

**Comment by azarbara** [comment]
could you please provide the manual wizard URL?

**Comment by w8tcha** [comment]
It can be found in the admin menu under Yaf Admin -> Upgrade -> install

**Comment by azarbara** [comment]
Thanks the problem resolved
