### ISSUE TITLE
what's new issue

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#21]
Ingo, 
the what's news module don't show latest post to all user's and show only for registered users,
any help please,

**Comment by azarbara** [comment]
here is the event log:
ModuleId:2029
ModuleDefId:131
FriendlyName:YAF What's New
ModuleControlSource:DesktopModules/YAF.WhatsNew/YafDnnWhatsNew.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:f1ff36f8-92fa-4397-8de1-98c63244d4dd
AssemblyVersion:7.4.0
PortalId:7
UserId:1
TabId:1323
RawUrl:/hara/
Referrer:http://rayeshmand.ir/hara/
UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
ExceptionHash:GdKI7+PFtJofYmdYmc4Ejw==
Message:Cannot insert the value NULL into column 'RankID', table 'rayeshmand_db.dbo.yaf_User'; column does not allow nulls. INSERT fails. The statement has been terminated.
StackTrace:
InnerMessage:Cannot insert the value NULL into column 'RankID', table '*****.yaf_User'; column does not allow nulls. INSERT fails. The statement has been terminated.
InnerStackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at YAF.Core.Data.DbAccessBase.Execute[T](Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction)
   at YAF.Classes.Data.LegacyDb.user_save(Object userID, Object boardID, Object userName, Object displayName, Object email, Object timeZone, Object languageFile, Object culture, Object themeFile, Object textEditor, Object useMobileTheme, Object approved, Object pmNotification, Object autoWatchTopics, Object dSTUser, Object hideUser, Object notificationType)
   at YAF.DotNetNuke.Components.Utils.UserImporter.CreateYafUser(UserInfo dnnUserInfo, MembershipUser dnnUser, Int32 boardID, Int32 portalID, YafBoardSettings boardSettings)
   at YAF.DotNetNuke.YafDnnWhatsNew.GetYafUserId()
   at YAF.DotNetNuke.YafDnnWhatsNew.BindData()

**Comment by w8tcha** [comment]
> the what's news module don't show latest post to all user's and show only for registered users,
any help please,

The Module Shows only the messages that are available for the user. For example if you want guests to see The Messages then you need to make sure that there have read access to the forum

**Comment by azarbara** [comment]
I recheck the user access.
![permission](https://cloud.githubusercontent.com/assets/5406334/13716238/18613b78-e7ef-11e5-9862-fac85c05ef4d.JPG)
it seems that there is another problem.

**Comment by azarbara** [comment]
@w8tcha there is no problem in user access, each time i refresh the page the following message add to site log,
`Cannot insert the value NULL into column 'RankID', table 'rayeshmand_db.dbo.yaf_User'; column does not allow nulls. INSERT fails. The statement has been terminated.`
could you please recheck this issue?

**Comment by azarbara** [comment]
i checked in another site with same environment and no problem found. this site is subportal without independent domain and maybe this is cause issue,  
i will set domain and recheck :)

**Comment by w8tcha** [comment]
Why you close the issue? were you able to resolve it? I need to check if i can reproduce this with a subportal

**Comment by azarbara** [comment]
this issue is in subportals with this format domain.com/sub, but in subportals with dedicated domain there isn't issue, now its better that, you fix this issue in this type of subportals,
my problem resolved by adding dedicated domain, and i think its better to close this issue(if you think i was wrong please Reopent the issue:))
